export default {
    allTypes: [
        "Bloodborne_Attire",
        "Bloodborne_AttireSet",
        "Bloodborne_AttireSlot",
        "Bloodborne_Badge",
        "Bloodborne_Boss",
        "Bloodborne_Element",
        "Bloodborne_Encounter",
        "Bloodborne_Gesture",
        "Bloodborne_Headstone",
        "Bloodborne_HunterTool",
        "Bloodborne_Imprint",
        "Bloodborne_KeyItem",
        "Bloodborne_Location",
        "Bloodborne_LootSource",
        "Bloodborne_Offhand",
        "Bloodborne_Phase",
        "Bloodborne_Quest",
        "Bloodborne_Rune",
        "Bloodborne_Shape",
        "Bloodborne_Weapon",
        "Bloodborne_WeaponVersion"
    ],
    searchString: "",
    currentResults: [],
    chaliceCheck: false,
    nothing: "",
}